/*
 * This file is generated by jOOQ.
 */
package com.kruczek.theravensystem.entity.tables.records;


import com.kruczek.theravensystem.entity.enums.RssChannelsRssType;
import com.kruczek.theravensystem.entity.tables.RssChannels;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RssChannelsRecord extends UpdatableRecordImpl<RssChannelsRecord> implements Record3<Integer, String, RssChannelsRssType> {

    private static final long serialVersionUID = -508892268;

    /**
     * Setter for <code>PUBLIC.RSS_CHANNELS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.RSS_CHANNELS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.RSS_CHANNELS.URL</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.RSS_CHANNELS.URL</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.RSS_CHANNELS.RSS_TYPE</code>.
     */
    public void setRssType(RssChannelsRssType value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.RSS_CHANNELS.RSS_TYPE</code>.
     */
    public RssChannelsRssType getRssType() {
        return (RssChannelsRssType) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, RssChannelsRssType> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, RssChannelsRssType> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RssChannels.RSS_CHANNELS.ID;
    }

    @Override
    public Field<String> field2() {
        return RssChannels.RSS_CHANNELS.URL;
    }

    @Override
    public Field<RssChannelsRssType> field3() {
        return RssChannels.RSS_CHANNELS.RSS_TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public RssChannelsRssType component3() {
        return getRssType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public RssChannelsRssType value3() {
        return getRssType();
    }

    @Override
    public RssChannelsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RssChannelsRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public RssChannelsRecord value3(RssChannelsRssType value) {
        setRssType(value);
        return this;
    }

    @Override
    public RssChannelsRecord values(Integer value1, String value2, RssChannelsRssType value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RssChannelsRecord
     */
    public RssChannelsRecord() {
        super(RssChannels.RSS_CHANNELS);
    }

    /**
     * Create a detached, initialised RssChannelsRecord
     */
    public RssChannelsRecord(Integer id, String url, RssChannelsRssType rssType) {
        super(RssChannels.RSS_CHANNELS);

        set(0, id);
        set(1, url);
        set(2, rssType);
    }
}
