/*
 * This file is generated by jOOQ.
 */
package com.kruczek.theravensystem.entity.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum RssChannelsRssType implements EnumType {

    TECHNICAL("TECHNICAL"),

    WORLD_NEWS("WORLD_NEWS"),

    MEMES("MEMES"),

    OTHER("OTHER");

    private final String literal;

    private RssChannelsRssType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "RSS_CHANNELS_RSS_TYPE";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
