/*
 * This file is generated by jOOQ.
 */
package com.kruczek.theravensystem.entity;


import com.kruczek.theravensystem.entity.tables.RssChannels;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.RSS_CHANNELS</code>.
     */
    public static final RssChannels RSS_CHANNELS = RssChannels.RSS_CHANNELS;
}
